### ISSUE TITLE
Add this open source repo into `Bangkok Open Source Festival '23`

### ISSUE THREAD

**Issue by pavaris-pm** [ksupasate/GPTForAnything#6]
@ksupasate I bring this issue up in order to inform you that i've added this repo to **Bangkok Open Source Festival '23** event since i think that your project can help a lot of people interesting in GPT applications. 

I think adding this repo to the event will help promoting it to others people and contributors to bring more interesting works into your repo. You can take a look at the event repo here [Bangkok Open Source Festival '23 repository](https://github.com/creatorsgarten/open.source.in.th), and your project will be shown in the [event website](https://open.source.in.th/) here.

**Comment by ksupasate** [comment]
I appreciate your support in this repository and including it in the Webring.

**Comment by pavaris-pm** [comment]
You're welcome!
